package quanLi.model;
// Generated Aug 28, 2019 5:31:39 PM by Hibernate Tools 5.2.3.Final

/**
 * Dangki generated by hbm2java
 */
public class Dangki implements java.io.Serializable {

	private Integer id;
	private Khoahoc khoahoc;
	private Student student;
	private int chiPhi;

	public Dangki() {
	}

	public Dangki(Khoahoc khoahoc, Student student, int chiPhi) {
		this.khoahoc = khoahoc;
		this.student = student;
		this.chiPhi = chiPhi;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Khoahoc getKhoahoc() {
		return this.khoahoc;
	}

	public void setKhoahoc(Khoahoc khoahoc) {
		this.khoahoc = khoahoc;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public int getChiPhi() {
		return this.chiPhi;
	}

	public void setChiPhi(int chiPhi) {
		this.chiPhi = chiPhi;
	}

}
