package quanLi.model;
// Generated Aug 28, 2019 5:31:39 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private Integer id;
	private String name;
	private int age;
	private Set dangkis = new HashSet(0);

	public Student() {
	}

	public Student(String name, int age) {
		this.name = name;
		this.age = age;
	}

	public Student(String name, int age, Set dangkis) {
		this.name = name;
		this.age = age;
		this.dangkis = dangkis;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public Set getDangkis() {
		return this.dangkis;
	}

	public void setDangkis(Set dangkis) {
		this.dangkis = dangkis;
	}

}
